### ISSUE TITLE
Broken with new python-kucoin

### ISSUE THREAD

**Issue by tnwhitwell** [jufkes/kucoinBot#6]
```
Traceback (most recent call last):
  File "bot.py", line 122, in <module>
    completedSellOrders = client.get_deal_orders(tokenPair, 'SELL')
AttributeError: 'Client' object has no attribute 'get_deal_orders'
```

**Comment by jufkes** [comment]
Are you using the docker container version or running the script straight from python?

**Comment by tnwhitwell** [comment]
I built the container fresh from the Dockerfile, as i'm a little wary of closed-book docker containers w/ no build log or github connection - you never know what someone could have snuck in (no offence intended - generally suspicious when API keys and money are concerned)

Is there a specific python-kucoin version i should tag in the pip install in the Dockerfile to get it working?

**Comment by jufkes** [comment]
No offense taken at all! I'm all for people being cautious. 

python-kucoin (0.1.0)

I'll pin that to the Dockerfile.

**Comment by jufkes** [comment]
Pinned. Go ahead and pull, build, and test.

**Comment by tnwhitwell** [comment]
Confirmed working!
Thanks!

On Mon, Jan 29, 2018 at 22:42, Chase Ufkes <notifications@github.com> wrote:
Pinned. Go ahead and pull, build, and test.

**Comment by jufkes** [comment]
You bet!
